version: '3.4'

services:
  attanapp:
    image: almogso/attenapp:latest
    links: 
      - db
    build: 
          context: .
          dockerfile: ./Dockerfile
    ports:
      - "80:5000"
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
    ports:
      - "8080:80"   
